//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemulShooter_GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemulShooter_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] Crosshair {
            get {
                object obj = ResourceManager.GetObject("Crosshair", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] dinput8_blocker {
            get {
                object obj = ResourceManager.GetObject("dinput8_blocker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [Wiimote1]
        ///Device = DInput/0/Keyboard Mouse
        ///Buttons/A = `Click 2`
        ///Buttons/B = `Click 0`
        ///Buttons/1 = 1
        ///Buttons/2 = 2
        ///Buttons/- = SUBTRACT
        ///Buttons/+ = ADD
        ///Buttons/Home = HOME
        ///Shake/X = `Click 1`
        ///Shake/Y = `Click 1`
        ///Shake/Z = `Click 1`
        ///Extension = Nunchuk
        ///Nunchuk/Buttons/C = LCONTROL
        ///Nunchuk/Buttons/Z = LSHIFT
        ///Nunchuk/Stick/Up = W
        ///Nunchuk/Stick/Down = S
        ///Nunchuk/Stick/Left = A
        ///Nunchuk/Stick/Right = D
        ///D-Pad/Up = UP
        ///D-Pad/Down = DOWN
        ///D-Pad/Left = LEFT
        ///D-Pad/Right = RIGHT
        ///Source = 1
        ///IR/Left [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string WiimoteNew_v4 {
            get {
                return ResourceManager.GetString("WiimoteNew_v4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [Wiimote1]
        ///Device = DInput/0/Keyboard Mouse
        ///Buttons/A = `Click 2`
        ///Buttons/B = `Click 0`
        ///Buttons/1 = `1`
        ///Buttons/2 = `2`
        ///Buttons/- = `3`
        ///Buttons/+ = `4`
        ///Buttons/Home = `5`
        ///IR/Up = `Cursor Y-`
        ///IR/Down = Cursor Y+
        ///IR/Left = Cursor X-
        ///IR/Right = Cursor X+
        ///Shake/X = `Click 1`
        ///Shake/Y = `Click 1`
        ///Shake/Z = `Click 1`
        ///Extension = Nunchuk
        ///Nunchuk/Buttons/C = LCONTROL
        ///Nunchuk/Buttons/Z = LSHIFT
        ///Nunchuk/Stick/Up = W
        ///Nunchuk/Stick/Down = S
        ///Nunchuk/Stick/Left = A
        ///Nunchuk/Stick/Right = D
        ///D-Pad/Up = [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string WiimoteNew_v5 {
            get {
                return ResourceManager.GetString("WiimoteNew_v5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_3 {
            get {
                object obj = ResourceManager.GetObject("xinput1_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
